steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_GCR_HOSTNAME/$_PROJECT_ID/$_SERVICE_NAME:latest"
      - .
      - "-f"
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$_PROJECT_ID/$_SERVICE_NAME:latest"
    id: Push

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=gcr.io/$_PROJECT_ID/$_SERVICE_NAME:latest
      - --region=$_DEPLOY_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars
      - "OPENAI_API_KEY=your-api-key-here"
      - --set-env-vars
      - "CHANNEL_ID=your-channel-id-here"
      - --set-env-vars
      - "CHANNEL_SECRET=your-channel-secret-here"
      - --set-env-vars
      - "INDEX_NAME=your-index-name-here"
      - --set-env-vars
      - "PINECONE_API_KEY=your-pinecone-api-key-here"
    id: Deploy

substitutions:
  _DEPLOY_REGION: asia-southeast1
  _GCR_HOSTNAME: gcr.io
  _SERVICE_NAME: your-service-name-here
  _PROJECT_ID: your-project-id-here
