service: workshop-ai
provider:
  profile: dodohandsome
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: prd
  region: ap-southeast-1
  memorySize: 256
  timeout: 30
  deploymentBucket:
    name: dodohandsome-ai
  deploymentPrefix: workshop-ai
  apiGateway:
    shouldStartNameWithService: true
plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin
functions:
  app:
    handler: bootstrap
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
custom:
  prune:
    automatic: true
    number: 3
  dotenv:
    path: .env
